/**
 * Hand-mirrored from docs/V2/BE/error-handling.md §7. Codes are a public
 * contract — adding one is safe, renaming or removing one is breaking.
 */
export const ERROR_CODE = {
  VALIDATION_FAILED: "VALIDATION_FAILED",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  BOOKING_SLOT_TAKEN: "BOOKING_SLOT_TAKEN",
  BOOKING_TOO_FAR_AHEAD: "BOOKING_TOO_FAR_AHEAD",
  BOOKING_IN_PAST: "BOOKING_IN_PAST",
  BOOKING_MIN_DURATION: "BOOKING_MIN_DURATION",
  BOOKING_CANCELLATION_WINDOW_CLOSED: "BOOKING_CANCELLATION_WINDOW_CLOSED",
  BOOKING_ALREADY_CANCELLED: "BOOKING_ALREADY_CANCELLED",
  WORKSPACE_NOT_BOOKABLE: "WORKSPACE_NOT_BOOKABLE",
  LOCATION_INACTIVE: "LOCATION_INACTIVE",
  AMENITY_IN_USE: "AMENITY_IN_USE",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  PAYMENT_ALREADY_PAID: "PAYMENT_ALREADY_PAID",
  PAYMENT_ALREADY_PENDING: "PAYMENT_ALREADY_PENDING",
  PAYMENT_NOT_REFUNDABLE: "PAYMENT_NOT_REFUNDABLE",
  PAYMENT_CUSTOMER_INCOMPLETE: "PAYMENT_CUSTOMER_INCOMPLETE",
  REFUND_EXCEEDS_REMAINDER: "REFUND_EXCEEDS_REMAINDER",
  PAYMENT_PROVIDER_ERROR: "PAYMENT_PROVIDER_ERROR",
  PAYMENT_PROVIDER_TIMEOUT: "PAYMENT_PROVIDER_TIMEOUT",
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
