export const ERROR_CODE = Object.freeze({
  // Generic
  VALIDATION_FAILED: "VALIDATION_FAILED",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  PROVIDER_ERROR: "PROVIDER_ERROR",
  PROVIDER_TIMEOUT: "PROVIDER_TIMEOUT",

  // Bookings
  BOOKING_SLOT_TAKEN: "BOOKING_SLOT_TAKEN",
  BOOKING_TOO_FAR_AHEAD: "BOOKING_TOO_FAR_AHEAD",
  BOOKING_IN_PAST: "BOOKING_IN_PAST",
  BOOKING_MIN_DURATION: "BOOKING_MIN_DURATION",
  BOOKING_CANCELLATION_WINDOW_CLOSED: "BOOKING_CANCELLATION_WINDOW_CLOSED",
  BOOKING_ALREADY_CANCELLED: "BOOKING_ALREADY_CANCELLED",

  // Workspaces / Locations / Amenities
  WORKSPACE_NOT_BOOKABLE: "WORKSPACE_NOT_BOOKABLE",
  LOCATION_INACTIVE: "LOCATION_INACTIVE",
  AMENITY_IN_USE: "AMENITY_IN_USE",

  // Users
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",

  // Payments
  PAYMENT_ALREADY_PAID: "PAYMENT_ALREADY_PAID",
  PAYMENT_ALREADY_PENDING: "PAYMENT_ALREADY_PENDING",
  PAYMENT_NOT_REFUNDABLE: "PAYMENT_NOT_REFUNDABLE",
  PAYMENT_CUSTOMER_INCOMPLETE: "PAYMENT_CUSTOMER_INCOMPLETE",
  REFUND_EXCEEDS_REMAINDER: "REFUND_EXCEEDS_REMAINDER",
  PAYMENT_PROVIDER_ERROR: "PAYMENT_PROVIDER_ERROR",
  PAYMENT_PROVIDER_TIMEOUT: "PAYMENT_PROVIDER_TIMEOUT",
});
